# Generated by Django 3.0.7 on 2020-08-29 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('disription', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 29, 11, 44, 55, 131992))),
            ],
        ),
    ]
