# Generated by Django 3.0.7 on 2020-09-11 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200829_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 11, 12, 48, 51, 882630)),
        ),
    ]
